apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-neoris-deploy
 namespace: neoris
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: neoris-deploy
 minReplicas: 1
 maxReplicas: 3
 metrics:
 - type: Resource
   resource:
    name: cpu
    target:
     type: Utilization
     averageUtilization: 70